	<link rel="shortcut icon" href="favicon.ico" />
	<link rel="stylesheet" href="../css/jquery-ui.css" />
	<link rel="stylesheet" href="../css/chosen.css">
	<link rel="stylesheet" href="../css/estilos-copropiedad.css" type="text/css" media="all">
	<link rel="stylesheet" href="../css/tablet.css" type="text/css"  media="all and (min-width: 640px) and (max-width: 1199px)">
	<link rel="stylesheet" href="../css/mobile.css" type="text/css" media="all and (min-width: 100px) and (max-width: 639px)">

	<link rel="alternate stylesheet" title="Aguamarina" href="../css/color1.css" type="text/css" media="all">
	<link rel="alternate stylesheet" title="Verde" href="../css/color2.css" type="text/css" media="all">
	<link rel="alternate stylesheet" title="Azul" href="../css/color3.css" type="text/css" media="all">
	<link rel="alternate stylesheet" title="Morado" href="../css/color4.css" type="text/css" media="all">
	<link rel="alternate stylesheet" title="Amarillo" href="../css/color5.css" type="text/css" media="all">
	<link rel="alternate stylesheet" title="Rojo" href="../css/color6.css" type="text/css" media="all">

	<!--[if IE 7 ]><link rel="stylesheet" href="css/ie7.css" type="text/css"> <![endif]-->

	<!-- For third-generation iPad with high-resolution Retina display: -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="../images/apple-touch-icon-144x144-precomposed.png">
	<!-- For iPhone with high-resolution Retina display: -->
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="../images/apple-touch-icon-114x114-precomposed.png">
	<!-- For first- and second-generation iPad: -->
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../images/apple-touch-icon-72x72-precomposed.png">
	<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
	<link rel="apple-touch-icon-precomposed" href="../images/apple-touch-icon-precomposed.png">