	<!--[if lte IE 9]>
	  <script src="js/html5.js"></script>
	<![endif]-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
	<script src="../../js/jquery.validate.js"></script>
	<!-- Template Engine -->
	<!--<script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
	<script src="js/copropiedad-template-engine.js"></script>-->
	<!--<script type="text/javascript" src="copropiedad-template-engine.js"></script>-->
	<!-- Variables de Sesion -->
	<!--<script src="../js/copropiedad-set_variables.js"></script>-->
	<!-- jquery alertas acción de cerrar y con html -->
	<script src="../../js/alertas.js"></script>
	<!-- además agregar alertas por js. Debe existir el div #alertas-automaticas, con data-alerts="alerts", data-titles opcional(tiene títulos para los diferentes tipos de alertas si se quieren agregar), y data-fade opcional (oculta el div en determinado número de milisegundos). Se puede usar para dar mensajes de sistema de guardado exitoso por ejemplo -->
	<script src="../../js/jquery.bsAlerts.js"></script>
	<!-- Script selector de copropiedad -->
	<script src="../../js/jquery-dd.js"></script>
	<script src="../../js/copropiedad-hoy.js"></script>
	<script>
	$(window).load(function(){
	  $('#cpLoading').fadeOut(2000);
	});
	</script>