                        <div class="panel" id="app-panel">
                            <div class="aplicaciones">
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Configurar Copropiedad">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/configuracion.png" />
                                            <h6>Configuración</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Contabilidad de la copropiedad">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/contabilidad.png" />
                                            <h6>Contabilidad</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Cartelera de anuncios">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/cartelera.png" />
                                            <h6>Cartelera</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Residentes">
                                        <div class="absoluto">
                                            <a href="residentes.html"><img src="template/images/residentes.png" />
                                            <h6>Residentes</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Proveedores">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/proveedores.png" />
                                            <h6>Proveedores</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Buzon de quejas">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/buzon.png" />
                                            <h6>Buzón de Quejas</h6></a>
                                        </div>
                                    </div>
                                    <div class="notificacion">
                                        <a href="#"><span>1</span></a>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Reserva de recursos">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/reservas.png" />
                                            <h6>Reservas</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Foros">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/foros.png" />
                                            <h6>Foros</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Documentos de la copropiedad">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/documentos.png" />
                                            <h6>Documentos</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Calendario de la copropiedad">
                                        <div class="absoluto">
                                            <a href="calendario.html"><img src="template/images/calendario.png" />
                                            <h6>Calendario</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Alertas">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/alertas.png" />
                                            <h6>Alertas</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Presupuesto">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/presupuesto.png" />
                                            <h6>Presupuesto</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Estado de cuenta">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/estado-cuenta.png" />
                                            <h6>Estado de Cuenta</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Encuestas">
                                        <div class="absoluto">
                                            <a href="encuestas.html"><img src="template/images/encuestas.png" />
                                            <h6>Encuestas</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Consejo">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/consejo.png" />
                                            <h6>Consejo</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Asamblea">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/asamblea.png" />
                                            <h6>Asamblea</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Micrositio">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/micrositio.png" />
                                            <h6>Micrositio</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Tareas">
                                        <div class="absoluto">
                                            <a href="tareas.html"><img src="template/images/tareas.png" />
                                            <h6>Tareas</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Solicitudes">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/solicitudes.png" />
                                            <h6>Solicitudes</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Comprar y vender">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/compraventa.png" />
                                            <h6>Compraventa</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Encomiendas">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/encomiendas.png" />
                                            <h6>Encomiendas</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Parqueaderos">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/parqueaderos.png" />
                                            <h6>Parqueaderos</h6></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="app">
                                    <div id="square" class="tooltip-boton" title="Votaciones">
                                        <div class="absoluto">
                                            <a href="#"><img src="template/images/votaciones.png" />
                                            <h6>Votaciones</h6></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both;"></div>
                          <a class="trigger btn fa fa-bars fa-lg fw" id="aplicaciones" href="#" title="aplicaciones" style="padding-left:8px; padding-right:8px;"></a>