<!-- CSS -->
  <link rel="shortcut icon" href="template/images/apple-touch-icon.png">
  <link rel="stylesheet" href="template/css/jquery-ui.min.css" />
  <!--<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">-->
  <link rel="stylesheet" href="template/css/chosen.min.css">
  <!-- Estilos Qtip -->
  <link rel="stylesheet" href="template/css/jquery.qtip.min.css">
  <link rel="stylesheet" href="template/css/copropiedad.min.css" type="text/css" media="all">
  <link rel="stylesheet" href="template/css/tablet.min.css" type="text/css"  media="all and (min-width: 640px) and (max-width: 1199px)">
  <link rel="stylesheet" href="template/css/mobile.min.css" type="text/css" media="all and (min-width: 100px) and (max-width: 639px)">

  <link rel="alternate stylesheet" title="Aguamarina" href="template/css/color1.min.css" type="text/css" media="all">
  <link rel="alternate stylesheet" title="Cyan" href="template/css/color2.min.css" type="text/css" media="all">
  <link rel="alternate stylesheet" title="Azul" href="template/css/color3.min.css" type="text/css" media="all">
  <link rel="alternate stylesheet" title="Morado" href="template/css/color4.min.css" type="text/css" media="all">
  <link rel="alternate stylesheet" title="Amarillo" href="template/css/color5.min.css" type="text/css" media="all">
  <link rel="alternate stylesheet" title="Anaranjado" href="template/css/color6.min.css" type="text/css" media="all">

  <!--[if IE 7 ]><link rel="stylesheet" href="css/ie7.css" type="text/css"> <![endif]-->

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="template/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPhone with high-resolution Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="template/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For first- and second-generation iPad: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="template/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="template/images/apple-touch-icon-precomposed.png">
  <!--[if lte IE 9]>
    <script src="js/html5.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="template/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="template/css/dataTables.responsive.min.css">
  <link rel="stylesheet" type="text/css" href="template/css/dataTables.colVis.min.css">
<!-- END CSS -->
