    <div id="cpLoading"><span class="fa fa-circle-o-notch fa-spin fa-fw"></span>Cargando...</div>
    <div id="cpImportando" teid="ms:html:4"><span class="fa fa-circle-o-notch fa-spin fa-fw"></span></div>
    <div id="cpEliminando" teid="ms:html:7"><span class="fa fa-circle-o-notch fa-spin fa-fw"></span></div>
    <div class="contenedor">
        <div class="logo">
           <a href="/">
              <h1>Copropiedad</h1>
           </a>
        </div>
        <div class="menus">
           <nav id="topmenu">
            <ul>
              <li class="drop">
                <a class="usuario" href="#" id="nusuario"><i class="fa fa-user fa-lg fa-fw"></i></a>
                <div class="dropdownContain">
                  <div class="dropOut">
                    <div class="triangle"></div>
                    <ul>
                      <li><a href="#" id="micuenta" teid="ge:html:2"><i class="fa fa-cog fa-fw"></i></a></li>
                      <li><a href="#" id="mispagos" teid="ge:html:6"><i class="fa fa-money fa-fw"></i></a></li>
                      <li><a href="#" id="miempresa" teid="ge:html:7"><i class="fa fa-building fa-fw"></i></a></li>
                    </ul>
                  </div>
                </div>
              </li>
              <li><a href="#" teid="ge:html:3" id="logout"><i class="fa fa-sign-out fa-fw"></i></a></li>
            </ul>
           </nav>
        </div>
        <div id="tutorial"></div>
    </div>
