                    	<div class="panel" id="new-panel">
                            <p><a href="#" id="open-crearcopropiedad">Crear Copropiedad</a></p>
                            <p><a href="#" id="open-crearcopropiedad">Crear Copropiedad</a></p>
                            <p><a href="#" id="open-crearcopropiedad">Crear Copropiedad</a></p>
                      </div>
                      <div style="clear:both;"></div>
                      <a class="trigger btn  fa fa-plus-circle fa-lg" id="nuevos" href="#" title="nuevos">&nbsp;Nuevo...</a>
                      