                        <div class="panel" id="pending-panel">
                            <ul>
                                <li>
                                    <div class="title" teid="ms:html:2"></div>
                                </li>
                            </ul>
                        </div>
                        <div style="clear:both;"></div>
                        <a class="trigger btn white" id="pendientes" href="#" title="pendientes"><span class="noti-pendientes" id="pending-counter">0</span><span id="pending-counter-text"></span></a>